name: Daily build and push

on:
  schedule:
  - cron: "0 6 * * *"
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Docker login
      uses: docker/login-action@v1 
      with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
    - 
      name: Build the Docker image all latest
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64,linux/arm/v8
          push: True
          tags: |
           ${{ github.repository }}:latest
    - 
      name: Build the Docker image amd64 latest
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: True
          tags: |
           ${{ github.repository }}:amd64-latest
    - 
      name: Build the Docker armV8 latest
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile.aarch64
          platforms: linux/arm/v8
          push: True
          tags: |
           ${{ github.repository }}:armv8-latest
    - 
      name: Build the Docker arm
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile.armhf
          platforms: linux/arm64
          push: True
          tags: |
           ${{ github.repository }}:arm64-latest
